# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 770a6277d7fe453febb3c39356a0fdf43abf3f7a7bd8db4b81b11e45adf547cb1f21cbc6df968eed60e9e678c736c6e9ab505f7c82f2c1d3d936fbd6849e5574

test:
  secret_key_base: 10e75973c312a81dd4957715378ad0a845ad1eb817aaccb4071f4b147878f8fe7752f2639f163bd25c5682ea67d70dba873cd0658c95390ca07a3e138ef28cf9

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
